### ISSUE TITLE
When changing sort mode for number of people by income, there are significant discrepancies

### ISSUE THREAD

**Issue by GaretWebster** [Gapminder/tools-page#175] opened 2021-03-18 18:51 UTC
When sorting by world or stack China looks like it's significantly ahead of inda. When sorting by none it's far behind.

I believe this is because they are incorrectly labeled based on the order you hover over them. Hovering from right to left seems to produce different results than left to right.

**Comment by angieskazka** [comment] 2021-03-29 10:13
👀  @GaretWebster thanks!
from what i understand, the labeling is correct, but the sorting order isn't. 
at some point china and india switch places, but they shouldn't as it takes attention away from smooth changes

it's a duplicate of https://github.com/Gapminder/tools-page/issues/129

**Closed by angieskazka** 2021-03-29 10:13 UTC
